name: CI Tests
on: 
  push: 
    branches-ignore:
      - develop
  pull_request:
jobs:
  npm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3.0.2
      - run: |
          cd react-web
          npm run test